**tfifd**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf =TfidfVectorizer()
doc_1="aww yeah it's all good bing bong bing bong"
doc_2="Might have a better chance if we put some trash cans out there."

In [ ]:
response=tfidf.fit_transform([doc_1,doc_2])

In [ ]:
print(len(tfidf.vocabulary_))

19


In [ ]:
tfidf.vocabulary_

{'all': 0,
 'aww': 1,
 'better': 2,
 'bing': 3,
 'bong': 4,
 'cans': 5,
 'chance': 6,
 'good': 7,
 'have': 8,
 'if': 9,
 'it': 10,
 'might': 11,
 'out': 12,
 'put': 13,
 'some': 14,
 'there': 15,
 'trash': 16,
 'we': 17,
 'yeah': 18}

In [ ]:
print(response)

  (0, 4)	0.5547001962252293
  (0, 3)	0.5547001962252293
  (0, 7)	0.27735009811261463
  (0, 0)	0.27735009811261463
  (0, 10)	0.27735009811261463
  (0, 18)	0.27735009811261463
  (0, 1)	0.27735009811261463
  (1, 15)	0.28867513459481287
  (1, 12)	0.28867513459481287
  (1, 5)	0.28867513459481287
  (1, 16)	0.28867513459481287
  (1, 14)	0.28867513459481287
  (1, 13)	0.28867513459481287
  (1, 17)	0.28867513459481287
  (1, 9)	0.28867513459481287
  (1, 6)	0.28867513459481287
  (1, 2)	0.28867513459481287
  (1, 8)	0.28867513459481287
  (1, 11)	0.28867513459481287


Sentiment **analysis**

In [ ]:
from textblob import TextBlob

In [ ]:
feedback1="he seems like a rude guy "
feedback2="he is very good guy "
blob1=TextBlob(feedback1)
blob2=TextBlob(feedback2)
print(blob1.sentiment)
print(blob2.sentiment)

Sentiment(polarity=-0.3, subjectivity=0.6)
Sentiment(polarity=0.9099999999999999, subjectivity=0.7800000000000001)


**N GRAMS**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

cv = CountVectorizer(ngram_range=(2,2))

corpus = ["he bought me a brownie shake lovehim",
          "he seems like a nice guy",
          "its gonna be a new day new start"]


X =cv.fit_transform(corpus)
#X = cv.fit_transform(corpus)
print(X.shape)
print(X)

print(X.toarray())


df = pd.DataFrame(X.toarray(), columns = cv.get_feature_names())
print(df)

(3, 15)
  (0, 5)	1
  (0, 1)	1
  (0, 9)	1
  (0, 2)	1
  (0, 14)	1
  (1, 6)	1
  (1, 13)	1
  (1, 8)	1
  (1, 12)	1
  (2, 7)	1
  (2, 4)	1
  (2, 0)	1
  (2, 10)	1
  (2, 3)	1
  (2, 11)	1
[[0 1 1 0 0 1 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 1 0 0 1 0 0 1 1 0 0 0]]
   be new  bought me  brownie shake  ...  nice guy  seems like  shake lovehim
0       0          1              1  ...         0           0              1
1       0          0              0  ...         1           1              0
2       1          0              0  ...         0           0              0

[3 rows x 15 columns]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


**BOW**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
 
text = """there was a man .
The man had a dog.
 The dog and the man walked."""
count_vectorizer=CountVectorizer()
bow=count_vectorizer.fit_transform(text.splitlines())
#print(count_vectorizer)
pd.DataFrame(bow.toarray(),columns=count_vectorizer.get_feature_names())


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


and  dog  had  man  the  there  walked  was
0    0    0    0    1    0      1       0    1
1    0    1    1    1    1      0       0    0
2    1    1    0    1    2      0       1    0

**word2vec**

In [ ]:
from nltk import word_tokenize
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
x = ["Done for the Yankees", "Happy birthday bird"]
y = [1,0]

In [ ]:
tokenizer = Tokenizer(num_words=20)

In [ ]:
tokenizer.fit_on_texts(x)

In [ ]:
sequences = tokenizer.texts_to_sequences(x)

In [ ]:
word_index = tokenizer.word_index
print(tokenizer.word_index)
print('Found %s unique tokens.' % len(word_index))

{'done': 1, 'for': 2, 'the': 3, 'yankees': 4, 'happy': 5, 'birthday': 6, 'bird': 7}
Found 7 unique tokens.


In [ ]:
print(sequences)

[[1, 2, 3, 4], [5, 6, 7]]


In [ ]:
max_length = 0
for review_number in range(len(sequences)):
  numberofwords=len(sequences[review_number])
  if (numberofwords) > (max_length):
    max_length = numberofwords
print(max_length)

4


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
data = pad_sequences(sequences, maxlen=max_length)
y = np.asarray(y)
print(data)
print('Shape of data tensor:', data.shape)

[[1 2 3 4]
 [0 5 6 7]]
Shape of data tensor: (2, 4)


**CountVectorizer**

In [ ]:

from sklearn.feature_extraction.text import CountVectorizer
  
document = ["well tom is a nice guy,
            "hai how are you how is your day going",
            "iam fine all are going good"]
  
# Create a Vectorizer Object
vectorizer = CountVectorizer()
  
vectorizer.fit(document)
  
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)
  
# Encode the Document
vector = vectorizer.transform(document)
  
# Summarizing the Encoded Texts
print("Encoded Document is:")
print(vector.toarray())

Vocabulary:  {'have': 7, 'good': 5, 'day': 2, 'hai': 6, 'how': 8, 'are': 1, 'you': 11, 'is': 10, 'your': 12, 'going': 4, 'iam': 9, 'fine': 3, 'all': 0}
Encoded Document is:
[[0 0 1 0 0 1 0 1 0 0 0 0 0]
 [0 1 1 0 1 0 1 0 2 0 1 1 1]
 [1 1 0 1 1 1 0 0 0 1 0 0 0]]
